# do NOT change the config version!
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# List of items that trigger ModGod
serviceItems:
  - WATER
  - STATIONARY_WATER
  - LAVA
  - STATIONARY_LAVA
  - FIRE
  - ICE
  - BEDROCK
  - WOOD_AXE
# Warm-up time until service mode is activated when holding a service item
# Optional. (0 - 10 seconds)
warmUpTime: 5
# grace period (time after switching to non-service item
# until service mode is deactivated)
# Optional. (0-10.0 seconds. 1/10th resolution)
gracePeriod: 1.5